general:
  kafka-topic: test-topic

spring:
  kafka:
    bootstrap-servers: dummy:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
